export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_LOADING = "FETCH_LOADING";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
//3
export const GET_BLOG_LOADING = "GET_BLOG_LOADING";
export const GET_BLOG_ERROR = "GET_BLOG_ERROR";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";

export const ADD_SERVICES_LOADING = "ADD_SERVICES_LOADING";
export const ADD_SERVICES_ERROR = "ADD_SERVICES_ERROR";
export const ADD_SERVICES_SUCCESS = "ADD_SERVICES_SUCCESS";

export const GET_SERVICES_LOADING = "GET_SERVICES_LOADING";
export const GET_SERVICES_ERROR = "GET_SERVICES_ERROR";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";

export const ADD_BLOG_LOADING = "ADD_BLOG_LOADING";
export const ADD_BLOG_ERROR = "ADD_BLOG_ERROR";
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS";

export const FILTER_DATA_BY_DATE ="FILTER_DATA_BY_DATE"
export const SEARCH_BY_ID_NAME="SEARCH_BY_ID_NAME"
export const SORT_DATA_BY_ID="SORT_DATA_BY_ID"
export const SORT_DATA_BY_SERVICE= "SORT_DATA_BY_SERVICE"